JMall/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('index.urls',namespace='index')),
    url(r'^', include('detail.urls',namespace='detail')),
    url(r'^', include('usercenter.urls',namespace='usercenter')),
    url(r'^', include('register2login.urls',namespace='register2login')),
    url(r'^', include('cart.urls',namespace='cart')),
    url(r'^', include('goodslist.urls',namespace='goodslist')),
]

cart/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^deleteHander/$',views.deleteHander,name='deleteHander'),
    url(r'^place_order/$',views.place_order,name='place_order'),
    url(r'^place_hander/$',views.place_hander,name='place_hander'),
]

usercenter/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from usercenter import views

urlpatterns = [
    url(r'^user_center_info/$',views.user_center_info,name='user_center_info'),
    url(r'^user_center_site/$',views.user_center_site,name='user_center_site'),
    url(r'^areal/$',views.areal,name='areal'),
    url(r'^user_center_order/$',views.user_center_order,name='user_center_order'),
    url(r'^pay/$',views.pay,name='pay'),
]

cart/views.py
from django.shortcuts import render,redirect
from django.http import *
from django.core.urlresolvers import reverse
from usercenter import der
from index.models import *
from datetime import datetime
import time
@der.login_yz
@der.login_name
def cart(request,dic):
    cart_list = dic['user'].cart_set.all().filter(is_delete=False)
    cart_good_list = []
    for cart in  cart_list:
        cart_good_list.append({
            "cart":cart,
            'good':Goods.objects.get(id=int(cart.goods_name))
        })
    dic = dict(dic,**{
        "lis":cart_good_list
    })

    return render(request,'cart/cart.html',dic)

@der.login_yz
def deleteHander(request):
    cart_id = request.POST.get('cart_id',None)
    if cart_id:
        cart = Cart.objects.get(id=int(cart_id))
        cart.is_delete = True
        cart.save()
        return JsonResponse({"response":'1'})

@der.login_yz
@der.login_name
def place_order(request,dic):
    '''
    结算
    :param request:
    :return:
    '''
    cart_id = []
    if request.method == 'GET':
        count = request.GET.get('count',None)
        good_id = int(request.GET.get('id',None))
        good_id = [good_id]
    else:
        count = request.POST.getlist('count',None)
        cart_id = request.POST.getlist('id',None)
        good_id=[]
        j = 0
        for i in cart_id:
            cart = Cart.objects.get(id=int(i))
            good_id.append(cart.goods_name)
            if int(count[j]) != cart.buy_count:
                cart.buy_count = int(count[j])
                cart.save()
            j += 1

    order_list = []
    freight = 10
    sumprice = 0
    for i in range(len(good_id)):
        goods = Goods.objects.get(id=int(good_id[i]))
        orderdic = {
            "goods":goods,
            "count":i+1,
            "sumtotal":goods.goods_price*int(count[i]),
            "goods_count":count[i]
        }
        if len(cart_id) > 0:
            orderdic["cart_id"] = cart_id[i]
        order_list.append(orderdic)
        sumprice += goods.goods_price*int(count[i])
    addr_list = dic['user'].user_addr_info.all()
    dic = dict(dic,**{
        'addr_list':addr_list,
        'order_list':order_list,
        'all_price':sumprice + freight,
        'goods_amount':len(good_id),
        'all_total':sumprice,
        'cart_id':cart_id,
        'freight':freight,
    })
    return render(request,'cart/place_order.html',dic)

@der.login_yz
@der.login_name
def place_hander(request,dic):
    '''
    提交订单后,处理页面跳转到用户订单页
    :param request:
    :param dic:
    :return:
    '''
    addr = request.POST.get('addr')
    goods_count = request.POST.get('goods_count')
    goods_id = request.POST.get('goods_id')  # 如果是立即购买的获取物品id
    cart_id = request.POST.get('cart_id')   # 如果是购物车结算的获取购物车id

    orders = Orders()
    orders.order_time = datetime.now()
    orders.order_number = str(int(time.time()))
    orders.user_order_id = dic['user'].id
    orders.addr = int(addr)
    orders.save()
    if cart_id and cart_id[0]:
        for i in cart_id:
            cart = Cart.objects.get(id=int(i))
            goods = Goods.objects.get(id=int(cart.goods_name))
            order_detail = orders.order_detail.create(goods_name=goods.goods_name,
                                                      goods_price=goods.goods_price,
                                                      buy_count=int(goods_count),
                                                      goods_id=goods_id)
            order_detail.save()
            cart.is_delete=True
            cart.save()
    else:
        goods = Goods.objects.get(id=int(goods_id))
        orders.order_detail.create(goods_name=goods.goods_name,
                                   goods_price=goods.goods_price,
                                   buy_count=goods_count,
                                   goods_id=goods_id)
    return redirect(reverse('usercenter:user_center_order'))

templates/cart/cart.html
{% extends 'base/base_user.html' %}
{% load static from staticfiles %}
{% block option %}
    购物车
{% endblock %}
{% block user_message %}

{% endblock %}
{% block content %}
    <div class="total_count">全部商品<em>2</em>件</div>
    <ul class="cart_list_th clearfix">
        <li class="col01">商品名称</li>
        <li class="col02">商品单位</li>
        <li class="col03">商品价格</li>
        <li class="col04">数量</li>
        <li class="col05">小计</li>
        <li class="col06">操作</li>
    </ul>
    <form action="/place_order/" method="POST">
        {% for l in lis %}
            <ul class="cart_list_td clearfix">
                <li class="col01"><input type="checkbox" name="id" value="{{ l.cart.id }}" id="per" checked="checked"></li>
                <li class="col02"><img src="/{{ l.good.img_path }}"></li>
                <li class="col03">{{ l.good.goods_name }}<br><em>{{ l.good.goods_price }}元/个</em></li>
                <li class="col04">1个</li>
                <li class="col05">{{ l.good.goods_price }}元</li>
                <li class="col06">
                    <div class="num_add">
                        <a href="javascript:;" class="add fl">+</a>
                        <input type="text" class="num_show fl" value="{{ l.cart.buy_count }}" name="count">
                        <a href="javascript:;" class="minus fl">-</a>
                    </div>
                </li>
                <li class="col07">4439元</li>
                <li class="col08"><a href="javascript:;" value="{{ l.cart.id }}">删除</a></li>
            </ul>
        {% endfor %}
        <ul class="settlements">
            <li class="col01"><input type="checkbox" name="" checked="checked" id="all"></li>
            <li class="col02">全选</li>
            <li class="col03">合计(不含运费): <span>¥</span><em>4439</em><br>共计<b>2</b>件商品</li>
            <li class="col04"><input type="submit" value="去结算" style="width: 100%;height: 76px;background-color: #ff3d3d;
                font-family: 'Microsoft YaHei';color: #fff;border: 0"></li>
        </ul>
    </form>

    <script type="text/javascript" src="{% static 'js/jquery-3.2.0.min.js' %}"></script>
    <script>
        function count() {
            $('.settlements li b').html($(':checkbox:checked:not(#all)').length);
            $('.total_count em').html($(':checkbox:checked:not(#all)').length);
        }
        function compute() {
            sum = 0;
            $('.cart_list_td').each(function () {
                oprice = parseFloat($(this).children('.col05').html().split('元')[0])*100*parseInt($(this).children('.col06')
                        .children('.num_add').children('.num_show').val())/100;
                $(this).children('.col07').html(oprice + '元');
                if($(this).children('li').children('input').prop('checked')){
                    sum = sum + oprice;
                }
            });
            $('.settlements .col03 em').html(sum);
        }
        $(':checkbox').click(function () {
            count();
        });
        $('.num_add input').change(function () {
            compute();
        });
        $('.num_add .add').click(function () {
            $(this).siblings('input').val(parseInt($(this).siblings('input').val()) + 1);
            $('.num_add input').change();
        });
        $('.num_add .minus').click(function () {
            if(parseInt($(this).siblings('input').val()) > 1){
                $(this).siblings('input').val(parseInt($(this).siblings('input').val()) - 1);
                $('.num_add input').change();
            }
        });
        count();
        compute();
        //全选全消
        $('#all').click(function () {
             if ($(this).prop('checked')) {
                $(':checkbox:not(#all)').prop('checked', true).parent().siblings('.col06').children().children('input').attr('name', 'count');
                compute();
                count()
            } else{
                 $(':checkbox:not(#all)').prop('checked', false).parent().siblings('.col06').children().children('input').attr('name', '');
                 compute();
                 count();
             }
        });
        $(':checkbox:not(#all)').click(function () {
            compute();
            if ($(this).prop('checked')) {
                $(this).parent().siblings('.col06').children().children('input').attr('name', 'count')
                $(this).attr('name', 'id')
            } else {
                $(this).parent().siblings('.col06').children().children('input').attr('name', '')
                $(this).attr('name', '')
            }
        });
        //删除
        $('.col08 a').click(function () {
            var cthis = $(this).parent().parent();
            $.ajax({
                url:'/deleteHander/',
                type:'POST',
                dataType:'JSON',
                data:{
                    'cart_id':$(this).attr('value')
                }
            }).done(function (data) {
                cthis.remove();
                compute();
                count();
            }).fail(function () {
                error_name = true;
                alert('服务器超时,请重试');
            })
        })
    </script>
{% endblock %}

templates/cart/place_order.html
{% extends 'base/base_user.html' %}
{% load static from staticfiles %}
{% block title %}
    全球购 - 提交订单
{% endblock %}
{% block option %}
    提交订单
{% endblock %}
{% block user_message %}

{% endblock %}

{% block content %}
    <h3 class="common_title">确认收货地址</h3>
    <form action="{% url 'cart:place_hander' %}" method="post" id="myform">
        <div class="common_list_con clearfix">
            <dl>
                <dt>寄送到: </dt>
                {% for addr in addr_list %}
                    <dd><input id="radio" type="radio" name="addr" value="{{ addr.id }}" {% if addr.default_addr == True %}
                        checked="true"
                    {% endif %}>
                        {{ addr.province }}{{ addr.city }}{{ addr.dis }}{{ addr.detail_addr }}{{ addr.address }}(收)
                        {% for ph in addr.phone %}
                            {% if forloop.counter <= 3 or forloop.counter > 7 %}
                                {{ ph }}
                                {% else %}*
                            {% endif %}
                        {% endfor %}

                    </dd>
                {% endfor %}
            </dl>
            <a href="{% url 'usercenter:user_center_site' %}" class="edit_site">编辑收货地址</a>
        </div>
        <h3 class="common_title">支付方式</h3>
        <div class="common_list_con clearfix">
            <div class="pay_style_con clearfix">
                <input type="radio" name="pay_style" checked="checked">
                <label class="crah">货到付款</label>
                <input type="radio" name="pay_style">
                <label class="weixin">微信支付</label>
                <input type="radio" name="pay_style">
                <label class="zhifubao"></label>
                <input type="radio" name="pay_style">
                <label class="bank">银行卡支付</label>
            </div>
        </div>
        <h3 class="common_title">商品列表</h3>
        <div class="common_list_con clearfix">
            <ul class="goods_list_th clearfix">
                <li class="col01">商品名称</li>
                <li class="col02">商品单位</li>
                <li class="col03">商品价格</li>
                <li class="col04">数量</li>
                <li class="col05">小计</li>
            </ul>
            {% for order in order_list %}
                <input type="hidden" value="{{ order.cart_id }}" name="cart_id">
                <input type="hidden" value="{{ order.goods_count }}" name="goods_count">
                <input type="hidden" value="{{ order.goods.id }}" name="goods_id">
                <ul class="goods_list_td clearfix">
                    <li class="col01">{{ order.count }}</li>
                    <li class="col02"><img src="/{{ order.goods.img_path }}"></li>
                    <li class="col03">{{ order.goods.goods_name }}</li>
                    <li class="col04">1个</li>
                    <li class="col05">{{ order.goods.goods_price }}</li>
                    <li class="col06">{{ order.goods_count }}</li>
                    <li class="col07">{{ order.sumtotal }}元</li>
                </ul>
            {% endfor %}

        </div>
        <div class="common_title">总金额结算</div>
        <div class="common_list_con">
            <div class="settle_con">
                <div class="total_goods_count">共<em>{{ goods_amount }}</em>件商品,总金额<b>{{ all_total }}元</b></div>
                <div class="transit">运费: <b>{{ freight }}元</b></div>
                <div class="total_pay">实付款: <b>{{ all_price }}元</b></div>
            </div>
        </div>
        <div class="order_submit clearfix">
            <input type="submit" name="" value="提交订单" id="order_btn" style="height: 40px;width: 160px;float: right;background-color: #47aa34;border: 0px;color:#fff;font-size: 16px;">
        </div>
    </form>
    <script type="text/javascript" src="{% static 'js/jquery-3.2.0.min.js' %}"></script>
    <script type="text/javascript">
        $('#radio').click(function () {
            $(this).attr('name','addr').siblings('#radio').attr('name','')
        })

        $('#myform').submit(function () {
            flag = false;
            if ($('.common_list_con dl dd input').length == 0){
                flag = false;
            }else {
                $('.common_list_con dl dd input').each(function () {
                    if ($(this).prop('checked')){
                        flag = true;
                    }
                })
            }
            if (flag == true){
                return true;
            }else {
                alert('地址未选择');
                return false;
            }
        })
    </script>
{% endblock %}