JMall/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('index.urls',namespace='index')),
    url(r'^', include('detail.urls',namespace='detail')),
    url(r'^', include('usercenter.urls',namespace='usercenter')),
    url(r'^', include('register2login.urls',namespace='register2login')),
    url(r'^', include('cart.urls',namespace='cart')),
    url(r'^', include('goodslist.urls',namespace='goodslist')),
]

cart/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^deleteHander/$',views.deleteHander,name='deleteHander'),
    url(r'^place_order/$',views.place_order,name='place_order'),
    url(r'^place_hander/$',views.place_hander,name='place_hander'),
]

goodslist/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from goodslist import views
urlpatterns = [
    url(r'^list/$',views.list,name='list'),
]

index/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from index import views

urlpatterns = [
    url(r'^index/$',views.index,name='indexPage'),
    url(r'^loginOut/$',views.loginOut,name='loginOut'),
]

register2login/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from register2login import views,viewsUtils

urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.login,name='login'),
    url(r'^verifycode/$',viewsUtils.verifycode,name='verifycode'),
    url(r'^changekw/$',views.changekw,name='changekw'),
]

usercenter/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from usercenter import views

urlpatterns = [
    url(r'^user_center_info/$',views.user_center_info,name='user_center_info'),
    url(r'^user_center_site/$',views.user_center_site,name='user_center_site'),
    url(r'^areal/$',views.areal,name='areal'),
    url(r'^user_center_order/$',views.user_center_order,name='user_center_order'),
    url(r'^pay/$',views.pay,name='pay'),
]

templates/base/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
{% block top %}
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到全球购</div>
        <div class="fr">
            <div class="login_info fl">
                欢迎您: <em>{{ user.username }}</em>
            </div>
            <div class="login_btn fl">
                <a href="{% url 'register2login:login' %}">登录</a>
                <span>|</span>
                <a href="{% url 'register2login:register' %}">注册</a>
            </div>
            <div class="login_info fl" id="login_btn_out">
                <span>|</span>
                <a href="/loginOut/">退出</a>
            </div>
            <div class="user_link fl">
                <span>|</span>
                <a href="{% url 'usercenter:user_center_info' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'cart:cart' %}">我的购物车</a>
                <span>|</span>
                <a href="#">我的订单</a>
            </div>
        </div>
    </div>
</div>
    <script src="{% static 'js/jquery-3.2.0.min.js' %}"></script>
    <script>
        $(function () {
            if ($('.login_info em').html() != ''){
                $('.login_info').show();
                $('.login_btn').hide();
                $('#login_btn_out').show();
            }else {
                $('.login_info').hide();
                $('.login_btn').show();
                $('#login_btn_out').hide();
            }
        })
    </script>
{% endblock %}

{% block menu %}

{% endblock %}

{% block content %}

{% endblock %}

{% block class %}
    <div class="footer"></div>
{% endblock %}

    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">最新活动</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>

    <div class="company_info">
         <p>CopyRight © 2017 广州全球购电子商务有限公司 All Rights Reserved</p>
         <p>电话：020-4545445    京ICP备686866888号</p>
    </div>

</body>
</html>

templates/base/base_index.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}
{% block title %}
    全球购-用户中心
{% endblock %}

{% block menu %}
    <div class="search_bar clearfix">
        <a href="{% url 'index:indexPage' %}" class="logo fl">
            <img src="{% static 'images/logo.png' %}">
        </a>
        <div class="search_con fl">
            <form target="_blank">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
        <div class="guest_cart fr">
            <i id="end"></i>
            <a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ number }}</div>
        </div>
    </div>

    {% block navlist %}
        <div class="navbar_con">
            <div class="navbar clearfix">
                <div class="subnav_con fl">
                    <h1>全部商品分类</h1>
                    <span></span>
                    <ul class="subnav">
                        {% for item in message %}
                            <li><a href="{% url 'goodslist:list' %}?order=id&&sort={{ item.sort.id }}" class="{{ item.sort.sort_class }}">{{ item.sort.sort_name }}</a> </li>
                        {% endfor %}

                    </ul>
                </div>
                <ul class="navlist fl">
                    <li><a href="#">首页</a></li>
                    <li class="interval">|</li>
                    <li><a href="#">手机商城</a> </li>
                    <li class="interval">|</li>
                    <li><a href="#">抽奖</a></li>
                </ul>
            </div>
        </div>
    {% endblock %}
{% endblock %}

templates/base/base_user.html
{% extends 'base/base.html' %}
{% load static from staticfiles%}
{% block title %}
    全球购 - 用户中心
{% endblock %}
{% block menu %}
    <div class="search_bar clearfix">
        <a href="{% url 'index:indexPage' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"> </a>
        <div class="sub_page_name fl">|    {% block option %}{% endblock %}</div>
        <div class="search_con fr">
            <form target="_blank">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
    </div>

        <div class="main_con clearfix">
            <div class="left_menu_con clearfix">
                <h3>用户中心</h3>
                <ul>
                    {% block tab_info %}
                        <li><a href="{% url 'usercenter:user_center_info' %}">· 个人信息</a> </li>
                    {% endblock %}
                    {% block tab_order %}
                        <li><a href="{% url 'usercenter:user_center_order' %}">· 全部订单</a> </li>
                    {% endblock %}
                    {% block tab_site %}
                        <li><a href="{% url 'usercenter:user_center_site' %}">· 收货地址</a></li>
                    {% endblock %}
                </ul>
            </div>
            {% block user_message %}{% endblock %}
        </div>
{% endblock %}