JMall/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('index.urls',namespace='index')),
    url(r'^', include('detail.urls',namespace='detail')),
    url(r'^', include('usercenter.urls',namespace='usercenter')),
    url(r'^', include('register2login.urls',namespace='register2login')),
    url(r'^', include('cart.urls',namespace='cart')),
    url(r'^', include('goodslist.urls',namespace='goodslist')),
]

cart/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^deleteHander/$',views.deleteHander,name='deleteHander'),
    url(r'^place_order/$',views.place_order,name='place_order'),
    url(r'^place_hander/$',views.place_hander,name='place_hander'),
]

usercenter/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from usercenter import views

urlpatterns = [
    url(r'^user_center_info/$',views.user_center_info,name='user_center_info'),
    url(r'^user_center_site/$',views.user_center_site,name='user_center_site'),
    url(r'^areal/$',views.areal,name='areal'),
    url(r'^user_center_order/$',views.user_center_order,name='user_center_order'),
    url(r'^pay/$',views.pay,name='pay'),
]

usercenter/views.py
from django.shortcuts import render,redirect
from usercenter import der
from index.models import *
from django.core.urlresolvers import reverse
from django.http import *
from django.core.paginator import Paginator

@der.login_yz
@der.login_name
def user_center_info(request,dic):
    if request.method == "GET":
        recentsee = dic['user'].user_recent_see.all()
        goods_list = []
        if recentsee:
            for i in recentsee:
                goods_list.append(Goods.objects.get(id=int(i.goods_name)))
        recv = goods_list[-5:]
        recv.reverse()
        dic = dict(dic,**{"recentsee":recv})
        return render(request,'usercenter/user_center_info.html',dic)
    else:
        addr = request.POST.get('addr')
        phone = request.POST.get('phone')
        if addr and str(phone).isdigit() and len(phone) == 11:
            dic['user'].phone = phone
            dic['user'].addr = addr
            dic['user'].save()
        return redirect(reverse('usercenter:user_center_info'))

@der.login_yz
@der.login_name
def user_center_site(request,dic):
    if request.method == 'GET':
        user = dic['user']
        addr_info = user.user_addr_info.all().filter(is_delete=False)
        list2 = []
        for i in addr_info:
            a = i.phone[0:]
            list2.append({
                "id":i.id,
                "province":i.province,
                "city":i.city,
                "dis":i.dis,
                "address":i.address,
                "phone":i.phone,
                "default_addr":i.default_addr
            })
        dic = dict(dic,**{"addr_info":list2})
        delete = request.GET.get("delete")
        change = request.GET.get("change")

        if delete:
            addr = AddrInfo.objects.get(id=delete)
            addr.is_delete = True
            addr.save()
            return redirect(reverse("usercenter:user_center_site"))
        if change:
            addr = AddrInfo.objects.get(id=change)
            try:
                default = AddrInfo.objects.filter(user=user.id).get(default_addr=True)
            except Exception as e:
                pass
            else:
                default.default_addr = False
                default.save()
                return redirect(reverse("usercenter:user_center_site"))

        return render(request,'usercenter/user_center_site.html',dic)
    else:
        addressee = request.POST.get('addressee')
        province = request.POST.get('province')
        city = request.POST.get('city')
        dis = request.POST.get('dis')
        detaaddr = request.POST('detaaddr')
        postcode = request.POST('postcode')
        phonenumber = request.POST('phonenumber')

        if addressee and province and city and detaaddr and str(phonenumber).isdigit() and len(phonenumber) == 11:
            addr_info = AddrInfo()
            addr_info.province = AreaInfo.objects.get(parent_id__exact=province)
            addr_info.city = AreaInfo.objects.get(parent_id__exact=city)
            if dis:
                addr_info.dis = AreaInfo.objects.get(parent_id__exact=dis)
            addr_info.address = addressee
            addr_info.default_addr =detaaddr
            addr_info.post_code = postcode
            addr_info.phone = phonenumber
            addr_info.user = dic['user']
            addr_info.save()
            print("成功存入")
            return redirect(reverse("usercenter:user_center_site"))
        else:
            return redirect(reverse("usercenter:user_center_site"))

def areal(request):
    list1 = AreaInfo.objects.filter(parent__isnull=True)
    list2 = []
    for a in list1:
        list2.append({
            "id":a.id,
            "title":a.title
        })
    return JsonResponse({'data':list2})

@der.login_yz
@der.login_name
def user_center_order(request,dic):
    order_list = Orders.objects.filter(is_delete=False).filter(user_order_id=dic['user'].id).order_by('-id').order_by('is_finish')
    p_index = request.GET.get("page",None)
    order_list2,p_list,p_index = pag_tab(order_list,p_index,2)
    if len(p_list) >= 3:
        '''页码显示页数'''
        if len(p_list) == p_index:
            p_list = p_list[p_index-3:p_index]
        elif p_index == 1:
            p_list = p_list[0:p_index+2]
        else:
            p_list = p_list[p_index-2:p_index+1]

    orders = []
    for order in order_list2:
        detail_list = []
        addr = AddrInfo.objects.get(id=order.addr)
        for i in order.order_detail.all():
            detail_list.append({
                "od":i,
                "good":i.goods,
            })
        orders.append({
            "order":order,
            "order_detail":detail_list,
            "addr":addr
        })
    dic = dict(dic,**{
        "order_list":orders,
        'p_list':p_list,
        "p_index":p_index
    })
    return render(request,'usercenter/user_center_order.html',dic)

def pag_tab(list1,p_index,num):
    '''
    分页
    :param list1:
    :param p_index:
    :param num:
    :return:
    '''
    p = Paginator(list1,num)
    if p_index == '' or p_index == None:
        p_index = '1'
    p_index = int(p_index)
    list2 = p.page(p_index)
    p_list = p.page_range
    return list2,p_list,p_index

@der.login_yz
@der.login_name
def pay(request,dic):
    order_id = request.GET.get('order',None)
    order = Orders.objects.get(id=int(order_id))
    order.is_finish = True
    order.save()
    return redirect(reverse("usercenter:user_center_order"))

templates/usercenter/user_center_info.html
{% extends 'base/base_user.html' %}
{% load static from staticfiles %}
{% block option %}
    用户中心
{% endblock %}
{% block tab_info %}
    <li><a href="{% url 'usercenter:user_center_info' %}" class="active">· 个人信息</a></li>
{% endblock %}

{% block user_message %}
    <div class="right_content clearfix">
        <form action="{% url 'usercenter:user_center_info' %}" method="post">
            <div class="info_con clearfix">
                <h3 class="common_title2">基本信息</h3>
                <ul class="user_info_list">
                    <li><span>用户名: </span>{{ user.username }}</li>
                    <li id="uphone"><span>联系方式: </span>{{ user.phone }}</li>
                    <li id="uaddr"><span>联系地址: </span>{{ user.addr }}
                        <div class="edit_btn" id="edit_btn">编辑</div>
                        <input class="edit_submit" type="submit" name="" value="提交">
                    </li>
                </ul>
            </div>
        </form>
    </div>

    <div class="has_view_list">
        <h3 class="common_title2 see_history">最近浏览</h3>
        <ul class="goods_type_list clearfix">
            {% for i in recentsee %}
                <li>
                    <a href="/detail/?goods_id={{ i.id }}"><img src="/{{ i.img_path }}"></a>
                    <h4><a href="/detail/?goods_id={{ i.id }}">{{ i.goods_name }}</a></h4>
                    <div class="operate">
                        <span class="price">¥ {{ i.goods_price }}</span>
                        <span class="unit">{{ i.goods_price }}/500g</span>
                        <a href="javascript:;" class="add_goods" title="加入购物车" value="{{ i.id }}"></a>
                    </div>
                </li>

            {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block content %}
    {#        <div class="right_content clearfix">#}
    {#            <form action="{% url 'usercenter:user_center_info' %}" method="post">#}
    {#                <div class="info_con clearfix">#}
    {#                    <h3 class="common_title2">基本信息</h3>#}
    {#                    <ul class="user_info_list">#}
    {#                        <li><span>用户名: </span>{{ user.username }}</li>#}
    {#                        <li id="uphone"><span>联系方式: </span>{{ user.phone }}</li>#}
    {#                        <li id="uaddr"><span>联系地址: </span>{{ user.addr }}#}
    {#                            <div class="edit_btn" id="edit_btn">编辑</div>#}
    {#                            <input class="edit_submit" type="submit" name="" value="提交">#}
    {#                        </li>#}
    {#                    </ul>#}
    {#                </div>#}
    {#            </form>#}
    {#        </div>#}

{#    <div class="has_view_list">#}
{#        <h3 class="common_title2 see_history">最近浏览</h3>#}
{#        <ul class="goods_type_list clearfix">#}
{#            {% for i in recentsee %}#}
{#                <li>#}
{#                    <a href="/detail/?goods_id={{ i.id }}"><img src="/{{ i.img_path }}"></a>#}
{#                    <h4><a href="/detail/?goods_id={{ i.id }}">{{ i.goods_name }}</a></h4>#}
{#                    <div class="operate">#}
{#                        <span class="price">¥ {{ i.goods_price }}</span>#}
{#                        <span class="unit">{{ i.goods_price }}/500g</span>#}
{#                        <a href="javascript:;" class="add_goods" title="加入购物车" value="{{ i.id }}"></a>#}
{#                    </div>#}
{#                </li>#}
{##}
{#            {% endfor %}#}
{#        </ul>#}
{#    </div>#}

    <script type="text/javascript" src="{% static 'js/jquery-3.2.0.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#edit_btn').click(function () {
                $("#uphone").html('<span>联系方式：</span><input type="text" name="phonenumber" value="{{user.phone}}">');
                $("#uaddr").html('<span>联系地址：</span><input type="text" name="addr" value="{{user.addr}}"><div class="edit_btn" id="edit_btn">编辑</div><input class="edit_submit"  type="submit" name="" value="提交">');
                $(":submit").css("display", "inline-block");
            });
            $('.add_goods').click(function () {
                thisgood = $(this).attr('value');
                //加入购物车
            })
        })
    </script>
{% endblock %}

templates/usercenter/user_center_order.html
{% extends 'base/base_user.html' %}
{% load static from staticfiles %}
{% block option %}
    用户中心
{% endblock %}
{% block tab_order %}
    <li><a href="{% url 'usercenter:user_center_order' %}" class="active">· 全部订单</a> </li>
{% endblock %}

{% block user_message %}
    <div class="right_content clearfix">
        <h3 class="common_title2">全部订单</h3>
        {% for order in order_list %}
             <ul class="order_list_th w978 clearfix">
                <li class="col01">{{ order.order.order_time }}</li>
                <li class="col02">订单号: {{ order.order.order_number }}</li>
                <li class="col02 stress">{% if order.order.is_finish == 1%}
                    已付款
                    {% else %}未支付
                {% endif %}</li>
             </ul>
             <table class="order_list_table w980">
                <tbody>
                    <tr>
                        <td width="55%">
                            {% for od in order.order_detail %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="/{{ od.good.img_path }}"></li>
                                    <li class="col02">{{ od.od.goods_name }}<em>{{ od.od.goods_price }}元/个</em></li>
                                    <li class="col03">{{ od.od.buy_count }}</li>
                                    <li class="col04">{{ od.od.goods_price }}元</li>
                                </ul>
                            {% endfor %}

                        </td>
                        <td width="15%"></td>
                        <td width="15%">{% if order.order.is_finish == 1%}
                             已付款
                            {% else %}未支付
                        {% endif %}</td>
                        <td width="15%">
                            {% if order.order.is_finish == 1 %}
                                <a href="javascript:;" class="oper_btn" id="oper_btn">查看物流</a>
                                {% else %}
                                    <a href="{% url 'usercenter:pay' %}?order={{ order.order.id }}" class="oper_btn">去付款</a>
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
             </table>
             <p style="display: none;">
                {{ order.addr.province }} {{ order.addr.city }} {{ order.addr.dis }} {{ order.addr.detail_addr }}（{{ order.addr.address }}
                收） {% for i in order.addr.phone %}{% if forloop.counter <= 3 or forloop.counter > 7 %}{{ i }}
                {% else %}*{% endif %}{% endfor %}
             </p>
        {% endfor %}
        <div class="pagenation">
            <a href="#" id="toleft">上一页</a>
            {% for index in p_list %}
                <a href="{% url 'usercenter:user_center_order' %}?page={{ index }}" class="{% if index == p_index %}
                    active
                {% endif %}"></a>
            {% endfor %}
            <a href="#" id="toright">下一页</a>
        </div>
    </div>
{% endblock %}
{% block content %}

    <script type="text/javascript" src="{% static 'js/jquery-3.2.0.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            function add(a, b) {
                var c, d, e;
                try {
                    c = a.toString().split(".")[1].length;
                } catch (f) {
                    c = 0;
                }
                try {
                    d = b.toString().split(".")[1].length;
                } catch (f) {
                    d = 0;
                }
                return e = Math.pow(10, Math.max(c, d)), (mul(a, e) + mul(b, e)) / e;
            }
            function mul(a, b) {
                var c = 0,
                    d = a.toString(),
                    e = b.toString();
                try {
                    c += d.split(".")[1].length;
                }catch (f){

                }
                try {
                    c += e.split(".")[1].length;
                }catch (f){

                }
                return Number(d.replace(".",""))*Number(e.replace(".",""))/Math.pow(10,c)
            }

            //分页
            var ahref = $('.pagenation .active').attr('href');
            var apage = ahref.split('page=');
            var max = parseInt($('#toright').prev('a').html());
            index = ahref.indexOf(apage[1]);
            left = parseInt(apage[1]) - 1;
            right = parseInt(apage[1]) + 1;
            if (left <= 0){
                left = 1;
            }
            if (right > max){
                right = max-1;
            }
            $('#toleft').attr({href:apage[0] + 'page=' + String(left)});
            $('#toright').attr({href:apage[0] + 'page=' + String(right)});

            //总价
            $('tbody tr td').each(function () {
                summ = 0;
                $(this).children('ul').children("em").each(function () {
                    summ +=  parseFloat($(this).html().split('元')[0]) * 100 * parseInt($(this).parent().siblings('.col03').html()) / 100;
                    $(this).parent().parent().parent().next().html(sum + '元');
                })
            });

            $("#oper_btn").click(function () {
                $(this).parent().parent().parent().parent().next('p').toggle();
            });
        })
    </script>
{% endblock %}

templates/usercenter/user_center_site.html
{% extends 'base/base_user.html' %}
{% load static from staticfiles %}
{% block option %}
    用户中心
{% endblock %}
{% block tab_site %}
    <li><a href="{% url 'usercenter:user_center_site' %}" class="active">. 收货地址</a> </li>
{% endblock %}

{% block user_message %}
<div class="right_content clearfix">
        <h3 class="common_title2>" style="font-size: 16px;margin-bottom: 10px">收货地址</h3>
        <div class="site_con">
            <dl id="thedl">
                {% for i in addr_info %}
                    <dd id="thedd">{{ i.province }}{{ i.city }}
                        {% if i.dis != None %}
                            {{ i.dis }}
                        {% endif %}
                        {{ i.detail_addr }} {{ i.address }}(收) {{ i.phone }}
                        {% if i.default_addr %}
                            <div class="edit_btn">默认地址</div>
                            {% else %}
                                <a href="{% url 'usercenter:user_center_site' %}?change={{ i.id }}" class="edit_btn" id="thisa">设为默认</a>

                        {% endif %}
                    </dd>

                {% endfor %}

            </dl>
        </div>
        <h3 class="common_title2">编辑地址</h3>
        <div class="site_con">
            <form action="{% url 'usercenter:user_center_site' %}" method="post">
                <div class="form_group from_arrer">
                    <label>收件人省市区:</label>
                    <select id="pro" name="province">
                        <option value="">请选择省</option>
                    </select>
                    <select id="city" name="city">
                        <option value="">请选择市</option>
                    </select>
                    <select id="dis" name="dis">
                        <option value="">请选择区县</option>
                    </select>
                </div>
                <div class="form_group form_group2">
                    <label>详细地址:</label>
                    <textarea class="site_area" name="detaaddr"></textarea>
                </div>
                <div class="form_group">
                    <label>邮编:</label>
                    <input type="text" name="postcode">
                </div>
                <div class="form_group">
                    <label>手机</label>
                    <input type="text" name="phonenumber">
                </div>
                <input type="submit" name="" value="提交" class="info_submit">
            </form>
        </div>
    </div>
{% endblock %}
{% block content %}


    <script type="text/javascript" src="{% static 'js/jquery-3.2.0.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $.get('/areal/',function (data) {
                pro = $('#pro');
                $.each(data.data,function (index, item) {
                    pro.append('<option value=' + item.id + '>' + item.title + '</option>');
                })
            });
            $('#pro').change(function () {
                $.get('/areal/' + $(this).val() + '/',function (data) {
                    city = $('#city');
                    city.empty().append('<option value="">请选择市</option>');
                    $('#dis').empty().append('<option value="">请选择区县</option>');
                    $.each(data.data, function (index, item) {
                        city.append('<option value=' + item.id + '>' + item.title + '</option>');
                    });
                })
            });
            $('#city').change(function () {
                $.get('/areal' + $(this).val() + '/', function (data) {
                    dis = $('#dis');

                    $.each(data.data, function (index, item) {
                        dis.append('<option value=' + item.id + '>' + item.title + '</option>');
                    });
                });

            });
        });
    </script>
{% endblock %}