JMall/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('index.urls',namespace='index')),
    url(r'^', include('detail.urls',namespace='detail')),
    url(r'^', include('usercenter.urls',namespace='usercenter')),
    url(r'^', include('register2login.urls',namespace='register2login')),
    url(r'^', include('cart.urls',namespace='cart')),
    url(r'^', include('goodslist.urls',namespace='goodslist')),
]

cart/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r'^cart/$',views.cart,name='cart'),
    url(r'^deleteHander/$',views.deleteHander,name='deleteHander'),
    url(r'^place_order/$',views.place_order,name='place_order'),
    url(r'^place_hander/$',views.place_hander,name='place_hander'),
]

index/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from index import views

urlpatterns = [
    url(r'^index/$',views.index,name='indexPage'),
    url(r'^loginOut/$',views.loginOut,name='loginOut'),
]

register2login/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from django.conf.urls import url
from register2login import views,viewsUtils

urlpatterns = [
    url(r'^register/$',views.register,name='register'),
    url(r'^login/$',views.login,name='login'),
    url(r'^verifycode/$',viewsUtils.verifycode,name='verifycode'),
    url(r'^changekw/$',views.changekw,name='changekw'),
]

register2login/views.py
from django.shortcuts import render,redirect,HttpResponse
from index.models import *
import hashlib
from datetime import datetime
from usercenter import der

def register(request):
    if request.method == "GET":
        return render(request,"register2login/register.html")
    elif request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("pwd")
        email = request.POST.get("email")
        if username and len(password) >= 6 and email:
            try:
                if UserInfo.objects.get(username=username):
                    return render(request, "register2login/register.html")
            except Exception as e:
                user = UserInfo()
                user.username = username
                n = hashlib.md5(password.encode('utf-8'))
                user.password = n.hexdigest()
                user.email = email
                user.reg_date = datetime.now()
                user.save()
                print('注册成功')
                return redirect('/login/')
            else:
                print("用户名已存在")
                return render(request, "register2login/register.html")
        else:
            return render(request, "register2login/register.html")

@der.login_name
def login(request,dic):
    if request.method == "GET":
        return render(request,"register2login/login.html",dic)
    elif request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("pwd")
        vcode = request.POST.get("vcode")
        # 先验证验证码防止暴力破解
        if vcode.upper() != request.session['verifycode']:
            return render(request, "register2login/login.html")
        if username and password:
            try:
                user = UserInfo.objects.get(username=username)
                # 如果用户名和密码都正确,登录成功
                n = hashlib.md5(password.encode('utf-8'))
                if user.password == n.hexdigest():
                    if request.POST.get('check') == 'on':
                        request.session['username'] = username
                    else:
                        request.session['username'] = username
                        # 超时测试
                        request.session.set_expiry(0)
                    return redirect('/index/')
                else:
                    return render(request, "register2login/login.html",{'error':{'password':'密码输入有误，请重新输入'}})
            except Exception as e:
                return render(request, "register2login/login.html")
        else:
            return render(request, "register2login/login.html",{'error':{'name':'请输入用户名','password':'请输入密码'}})

def changekw(request):
    '''
    忘记密码
    :param request:
    :return:
    '''
    if request.method == 'GET':
        return render(request,'register2login/changekw.html')
    else:
        username = request.POST.get("username",None)
        password = request.POST.get("pwd",None)
        email = request.POST.get('email',None)

        if username and len(password) >= 6 and email:
            user = UserInfo.objects.get(username=username)
            if user.email == email:
                n = hashlib.md5(password.encode('utf-8'))
                user.password = n.hexdigest()
                user.save()
                return redirect('/login/')
            else:
                return render(request, 'register2login/changekw.html',{'error':{'email':'邮箱错误,请重新输入'}})

        return render(request, 'register2login/changekw.html')

templates/register2login/changekw.html
{%extends 'base/base.html'%}
{% load static from staticfiles %}

{%block title%}全球购-密码修改{%endblock%}
{%block top%}
<script type="text/javascript" src="{% static 'js/jquery-3.2.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/changekw.js'%}"></script>
{%endblock%}


{%block content%}
<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo" href="{% url 'index:indexPage' %}"><img src="{% static 'images/logo.png' %}"></a>
			<div class="reg_slogan">只要你想到  ·   就在全球购</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>密码修改</h1>
				<a href="{% url 'register2login:login'%}">登录</a>
			</div>
			<div class="reg_form clearfix" id='reg_form'>
				<form method="post" action="{% url 'register2login:changekw'%}">
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="username" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱验证:</label>
						<input type="text" name="email" id="email">
						<div class="error_tip fl" id="email_error">{{error.email}}</div>
					</li>					
					<li>
						<label>新密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>

					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意“全球购用户协议”</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="修 改" name="">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
	<script type="text/javascript">
		if ($('#email_error').html() != '') {$('#email_error').show()};
	</script>
{%endblock%}

templates/register2login/login.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}
{% block title %}
    全球购 - 登录
{% endblock %}

{% block content %}
    <script type="text/javascript" src="{% static 'js/jquery-3.2.0.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#verifychangecode').css('cursor','pointer').click(function () {
                $('#verifycode').attr('src','/verifycode/?' + Math.random())
            })
        })
    </script>

    <div class="login_top clearfix">
        <a href="{% url 'index:indexPage' %}" class="login_logo">
            <img src="{% static 'images/register_logo.png' %}">
        </a>
    </div>
    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">不远千里   ·   极速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="{% url 'register2login:register' %}">立即注册</a>
                </div>
                <div class="form_input">
                    <form action="{% url 'register2login:login' %}" method="post">
                        <input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{ user.username }}">
                        <div class="user_error">{{ error.name }}</div>

                        <input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
                        <div class="pwd_error">{{ error.password }}</div>

                        <div class="yzm_check">
                            <!--验证码-->
                            <input type="text" class="yzm_input" name="vcode">
                            <img id="verifycode" class="verifycode" src="/verifycode/" name='vecode' alt="验证码">
                            <span id="verifychangecode">看不清楚，换一个</span>
                        </div>
                        <div class="more_input clearfix">
                            <input class="more_input_check" type="checkbox" name="check">
                            <label>记住用户名</label>
                            <a href="{% url 'register2login:changekw' %}">忘记密码</a>
                        </div>
                        <input type="submit" name="" value="登录" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        if($('.user_error').html() != ''){
            $('.user_error').show();
        }
        if ($('.pwd_error').html() != ''){
            $('.pwd_error').show();
        }
    </script>
{% endblock %}
{% block class %}
    <div class="footer no-mp"></div>
{% endblock %}

templates/register2login/register.html
{% extends 'base/base.html' %}
{% load static from staticfiles %}
{% block title %}
    全球购 - 注册
{% endblock %}

{% block top %}
    <script type="text/javascript" src="{% static 'js/jquery-3.2.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="register_con">
        <div class="l_con fl">
            <a class="reg_logo" href="{% url 'index:indexPage' %}">
                <img src="{% static 'images/register_logo.png' %}">
            </a>
            <div class="reg_slogan">只要你想到  ·   就在全球购</div>
            <div class="reg_banner"></div>
        </div>
        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="{% url 'register2login:login' %}">登录</a>
            </div>
            <div class="reg_form clearfix">
                <form method="post" action="{% url 'register2login:register' %}">
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="username" id="username">
                            <span class="error_tip">提示信息</span>
                        </li>

                        <li>
                            <label>密码:</label>
                            <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>

                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label>同意“全球购用户协议”</label>
						    <span class="error_tip2">提示信息</span>
                        </li>

                        <li class="reg_sub">
						    <input type="submit" value="注 册" name="">
					    </li>
                    </ul>
                </form>
            </div>
        </div>
    </div>
{% endblock %}